/**
 * Function profile builder — assembles FunctionProfile domain objects from
 * Ghidra functions, normalized call edges, and the evidence store.
 */
import { type Evidence, type FunctionProfile } from '../../shared/types.js';
import { type GhidraFunction } from '../ghidra/validator.js';
import { type NormalizedEdges } from './callEdgeNormalizer.js';

/** Regex that matches Ghidra auto-generated function names like FUN_00401000 */
const AUTO_GENERATED_RE = /^FUN_[0-9a-fA-F]+$/;

/**
 * Builds FunctionProfile objects from Ghidra output.
 *
 * - Callers/callees are taken from the normalized edge map (not raw Ghidra output)
 * - evidenceIds links to function evidence in the store
 * - decompilationEvidenceIds links to decompilation evidence in the store
 * - autoGenerated is re-derived from the name pattern (not trusted from Ghidra raw)
 */
export function buildFunctionProfiles(
  ghidraFunctions: GhidraFunction[],
  normalizedEdges: Map<string, NormalizedEdges>,
  evidence: Evidence[],
): FunctionProfile[] {
  // Build lookup: address → function evidence ID
  const functionEvidenceIds = new Map<string, string>();
  const decompEvidenceIds = new Map<string, string>();

  for (const evd of evidence) {
    if (evd.kind === 'function' && evd.location?.address) {
      functionEvidenceIds.set(evd.location.address, evd.id);
    }
    if (evd.kind === 'decompilation' && evd.location?.functionAddress) {
      decompEvidenceIds.set(evd.location.functionAddress, evd.id);
    }
  }

  const profiles: FunctionProfile[] = [];

  for (const fn of ghidraFunctions) {
    const edges = normalizedEdges.get(fn.address) ?? { callers: [], callees: [] };
    const evdId = functionEvidenceIds.get(fn.address);
    const decompEvdId = decompEvidenceIds.get(fn.address);

    profiles.push({
      address: fn.address,
      name: fn.name,
      autoGenerated: AUTO_GENERATED_RE.test(fn.name),
      callers: edges.callers,
      callees: edges.callees,
      apiReferences: fn.referencedImports,
      stringReferences: fn.referencedStrings,
      evidenceIds: evdId !== undefined ? [evdId] : [],
      decompilationEvidenceIds: decompEvdId !== undefined ? [decompEvdId] : [],
      selectionScore: fn.selectionScore,
      selectionReasons: fn.selectionReasons,
    });
  }

  return profiles;
}
