/**
 * Validates and parses the JSON output produced by CodeArchaeologistScript.java.
 */
import * as fs from 'fs/promises';

export interface GhidraFunction {
  address: string;
  name: string;
  autoGenerated: boolean;
  callers: string[];
  callees: string[];
  referencedImports: string[];
  referencedStrings: string[];
  selectionScore: number;
  selectionReasons: string[];
  decompilation: string | null;
}

export interface GhidraRawOutput {
  programLanguage?: string;
  entryPoint?: string;
  totalFunctions?: number;
  functions: GhidraFunction[];
}

/**
 * Reads, parses, and validates the Ghidra output JSON file.
 * Throws a descriptive error on any validation failure.
 */
export async function validateGhidraOutput(outputJsonPath: string): Promise<GhidraRawOutput> {
  let content: string;
  try {
    content = await fs.readFile(outputJsonPath, 'utf8');
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`Ghidra output file not found or unreadable at "${outputJsonPath}": ${msg}`);
  }

  if (content.trim().length === 0) {
    throw new Error(`Ghidra output file is empty: "${outputJsonPath}"`);
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(content);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`Ghidra output is not valid JSON at "${outputJsonPath}": ${msg}`);
  }

  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new Error(`Ghidra output must be a JSON object, got: ${typeof parsed}`);
  }

  const obj = parsed as Record<string, unknown>;
  if (!Array.isArray(obj['functions'])) {
    throw new Error(
      `Ghidra output missing required "functions" array. Keys present: ${Object.keys(obj).join(', ')}`,
    );
  }

  return parsed as GhidraRawOutput;
}
