/**
 * Inference rules tests.
 *
 * Mandatory anti-overclaim tests + positive signal tests.
 */
import {
  networkCommunicationRule,
  authenticationCredentialsRule,
  databaseInteractionRule,
  cryptographicOperationsRule,
  windowsInstallationRule,
  registryConfigPersistenceRule,
  serviceDriverLifecycleRule,
  type EvidenceContext,
} from '../rules.js';
import { type Evidence, type ExtractedString, type FunctionProfile } from '../../../shared/types.js';

// ── Helpers ────────────────────────────────────────────────────────────────────

function makeStringEvidence(value: string, id = `evd-str-${value.slice(0, 8)}`): Evidence {
  return {
    id,
    kind: 'string',
    sourceTool: 'strings',
    classification: 'observed',
    summary: `String: ${value}`,
    data: { value },
  };
}

function makeImportEvidence(dll: string, fns: string[], id: string): Evidence {
  return {
    id,
    kind: 'import',
    sourceTool: 'pe-parser',
    classification: 'observed',
    summary: `Import DLL: ${dll} (${fns.length} function(s))`,
    data: { dll, functions: fns },
  };
}

function makeExtractedString(value: string): ExtractedString {
  return {
    value,
    encoding: 'ascii',
    offset: 0,
    category: 'other',
  };
}

function makeFunctionProfile(name: string, autoGenerated = false): FunctionProfile {
  return {
    address: '0x00401000',
    name,
    autoGenerated,
    callers: [],
    callees: [],
    apiReferences: [],
    stringReferences: [],
    evidenceIds: [],
    decompilationEvidenceIds: [],
    selectionScore: 0,
    selectionReasons: [],
  };
}

function emptyCtx(): EvidenceContext {
  return { evidence: [], functionProfiles: [], imports: [], strings: [] };
}

// ── Anti-overclaim tests ──────────────────────────────────────────────────────

describe('Anti-overclaim: network rule', () => {
  test('SendMessageW + SendDlgItemMessageW do NOT produce network inference', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      imports: [{ dll: 'user32.dll', functions: ['SendMessageW', 'SendDlgItemMessageW', 'PostMessageW', 'SendMessageA', 'PostMessageA'] }],
      evidence: [makeImportEvidence('user32.dll', ['SendMessageW', 'SendDlgItemMessageW', 'PostMessageW'], 'evd-imp-0001')],
    };
    const inferences = networkCommunicationRule.evaluate(ctx);
    // These are Windows messaging APIs, NOT network — rule must produce nothing or only LOW
    const networkInferences = inferences.filter(i => i.confidence !== 'low');
    expect(networkInferences).toHaveLength(0);
    // Also: no medium or high inference should exist
    for (const inf of inferences) {
      expect(['low', 'not-applicable']).toContain(inf.confidence);
    }
  });

  test('Single URL string alone does NOT produce medium or high network inference', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      evidence: [makeStringEvidence('https://example.com/api', 'evd-str-0001')],
      strings: [makeExtractedString('https://example.com/api')],
    };
    const inferences = networkCommunicationRule.evaluate(ctx);
    for (const inf of inferences) {
      expect(inf.confidence).not.toBe('medium');
      expect(inf.confidence).not.toBe('high');
    }
  });

  test('URL string alone produces at most LOW confidence', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      evidence: [makeStringEvidence('https://api.example.com/endpoint', 'evd-str-0001')],
      strings: [makeExtractedString('https://api.example.com/endpoint')],
    };
    const inferences = networkCommunicationRule.evaluate(ctx);
    if (inferences.length > 0) {
      expect(inferences[0]!.confidence).toBe('low');
    }
    // 0 or 1 low-confidence inference is acceptable
    expect(inferences.length).toBeLessThanOrEqual(1);
  });
});

describe('Anti-overclaim: authentication rule', () => {
  test('Generic "password"/"login" strings alone do NOT produce high-confidence auth inference', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      evidence: [
        makeStringEvidence('password', 'evd-str-0001'),
        makeStringEvidence('login', 'evd-str-0002'),
        makeStringEvidence('username', 'evd-str-0003'),
      ],
      strings: [
        makeExtractedString('password'),
        makeExtractedString('login'),
        makeExtractedString('username'),
      ],
    };
    const inferences = authenticationCredentialsRule.evaluate(ctx);
    for (const inf of inferences) {
      expect(inf.confidence).not.toBe('high');
      expect(inf.confidence).not.toBe('medium');
    }
  });

  test('Generic auth strings alone produce at most LOW confidence', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      evidence: [
        makeStringEvidence('token', 'evd-str-0001'),
        makeStringEvidence('auth', 'evd-str-0002'),
      ],
      strings: [makeExtractedString('token'), makeExtractedString('auth')],
    };
    const inferences = authenticationCredentialsRule.evaluate(ctx);
    for (const inf of inferences) {
      expect(['low', 'not-applicable']).toContain(inf.confidence);
    }
  });
});

describe('Anti-overclaim: database rule', () => {
  test('Generic SQL strings alone do NOT produce high-confidence database inference', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      evidence: [
        makeStringEvidence('SELECT * FROM users WHERE id = 1', 'evd-str-0001'),
        makeStringEvidence('INSERT INTO logs', 'evd-str-0002'),
      ],
      strings: [
        makeExtractedString('SELECT * FROM users WHERE id = 1'),
        makeExtractedString('INSERT INTO logs'),
      ],
    };
    const inferences = databaseInteractionRule.evaluate(ctx);
    for (const inf of inferences) {
      expect(inf.confidence).not.toBe('high');
      expect(inf.confidence).not.toBe('medium');
    }
  });

  test('Generic SQL strings alone produce at most LOW confidence', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      evidence: [makeStringEvidence('SELECT name FROM table', 'evd-str-0001')],
      strings: [makeExtractedString('SELECT name FROM table')],
    };
    const inferences = databaseInteractionRule.evaluate(ctx);
    for (const inf of inferences) {
      expect(['low', 'not-applicable']).toContain(inf.confidence);
    }
  });
});

describe('Anti-overclaim: cryptography rule', () => {
  test('CryptAcquireContextW alone produces at most MEDIUM confidence', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      imports: [{ dll: 'advapi32.dll', functions: ['CryptAcquireContextW'] }],
      evidence: [makeImportEvidence('advapi32.dll', ['CryptAcquireContextW'], 'evd-imp-0001')],
    };
    const inferences = cryptographicOperationsRule.evaluate(ctx);
    for (const inf of inferences) {
      expect(inf.confidence).not.toBe('high');
      expect(['medium', 'low', 'not-applicable']).toContain(inf.confidence);
    }
  });

  test('CryptAcquireContextW alone does not claim specific encrypted data flow', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      imports: [{ dll: 'advapi32.dll', functions: ['CryptAcquireContextW'] }],
      evidence: [makeImportEvidence('advapi32.dll', ['CryptAcquireContextW'], 'evd-imp-0001')],
    };
    const inferences = cryptographicOperationsRule.evaluate(ctx);
    for (const inf of inferences) {
      // Statement should NOT claim "encrypts data" or similar strong claim
      expect(inf.statement.toLowerCase()).not.toContain('encrypted data flow');
      // Limitations must reference this anti-overclaim
      const allLimitations = inf.limitations.join(' ').toLowerCase();
      expect(allLimitations).toContain('cryptacquirecontextw');
    }
  });
});

describe('Anti-overclaim: registry/installation rule', () => {
  test('Registry APIs alone are NOT sufficient for installation inference at medium/high', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      imports: [{ dll: 'advapi32.dll', functions: ['RegCreateKeyExW', 'RegSetValueExW', 'RegOpenKeyExW'] }],
      evidence: [makeImportEvidence('advapi32.dll', ['RegCreateKeyExW', 'RegSetValueExW', 'RegOpenKeyExW'], 'evd-imp-0001')],
    };
    const inferences = windowsInstallationRule.evaluate(ctx);
    for (const inf of inferences) {
      expect(inf.confidence).not.toBe('medium');
      expect(inf.confidence).not.toBe('high');
    }
  });

  test('Registry APIs alone produce at most LOW confidence for installation', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      imports: [{ dll: 'advapi32.dll', functions: ['RegCreateKeyExW', 'RegSetValueExW', 'RegDeleteKeyExW', 'RegOpenKeyExW'] }],
      evidence: [makeImportEvidence('advapi32.dll', ['RegCreateKeyExW', 'RegSetValueExW', 'RegDeleteKeyExW', 'RegOpenKeyExW'], 'evd-imp-0001')],
    };
    const inferences = windowsInstallationRule.evaluate(ctx);
    for (const inf of inferences) {
      expect(['low', 'not-applicable']).toContain(inf.confidence);
    }
  });
});

describe('Anti-overclaim: function naming', () => {
  test('FUN_* function name has autoGenerated=true', () => {
    const fp = makeFunctionProfile('FUN_00401000', true);
    expect(fp.autoGenerated).toBe(true);
    expect(fp.name).toMatch(/^FUN_/);
  });

  test('FUN_* function name should never be treated as a recovered source name', () => {
    const fp = makeFunctionProfile('FUN_00401234', true);
    // autoGenerated=true means callers must not present this as a known source name
    expect(fp.autoGenerated).toBe(true);
  });
});

// ── Positive tests ────────────────────────────────────────────────────────────

describe('Positive: database inference', () => {
  test('ODBC APIs + SQL strings in same context → HIGH confidence', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      imports: [{ dll: 'odbc32.dll', functions: ['SQLConnectW', 'SQLExecDirectW', 'SQLFetch', 'SQLAllocHandle'] }],
      evidence: [
        makeImportEvidence('odbc32.dll', ['SQLConnectW', 'SQLExecDirectW', 'SQLFetch'], 'evd-imp-0001'),
        makeStringEvidence('SELECT id, name FROM users WHERE active=1', 'evd-str-0001'),
        makeStringEvidence('Driver={SQL Server};Server=localhost', 'evd-str-0002'),
      ],
      strings: [
        makeExtractedString('SELECT id, name FROM users WHERE active=1'),
        makeExtractedString('Driver={SQL Server};Server=localhost'),
      ],
    };
    const inferences = databaseInteractionRule.evaluate(ctx);
    expect(inferences).toHaveLength(1);
    expect(inferences[0]!.confidence).toBe('high');
    expect(inferences[0]!.ruleId).toBe('database-interaction');
  });
});

describe('Positive: network inference', () => {
  test('WinHTTP APIs + URL strings → HIGH confidence', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      imports: [{ dll: 'winhttp.dll', functions: ['WinHttpOpen', 'WinHttpConnect', 'WinHttpSendRequest'] }],
      evidence: [
        makeImportEvidence('winhttp.dll', ['WinHttpOpen', 'WinHttpConnect', 'WinHttpSendRequest'], 'evd-imp-0001'),
        makeStringEvidence('https://api.example.com/data', 'evd-str-0001'),
      ],
      strings: [makeExtractedString('https://api.example.com/data')],
    };
    const inferences = networkCommunicationRule.evaluate(ctx);
    expect(inferences).toHaveLength(1);
    expect(inferences[0]!.confidence).toBe('high');
    expect(inferences[0]!.ruleId).toBe('network-communication');
    expect(inferences[0]!.statement).toContain('WinHTTP');
  });
});

describe('Positive: service-driver lifecycle', () => {
  test('SCM APIs + service strings → HIGH confidence', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      imports: [{ dll: 'advapi32.dll', functions: ['OpenSCManagerW', 'CreateServiceW', 'StartServiceW', 'CloseServiceHandle'] }],
      evidence: [
        makeImportEvidence('advapi32.dll', ['OpenSCManagerW', 'CreateServiceW', 'StartServiceW', 'CloseServiceHandle'], 'evd-imp-0001'),
        makeStringEvidence('C:\\Windows\\System32\\drivers\\mydriver.sys', 'evd-str-0001'),
      ],
      strings: [makeExtractedString('C:\\Windows\\System32\\drivers\\mydriver.sys')],
    };
    const inferences = serviceDriverLifecycleRule.evaluate(ctx);
    expect(inferences).toHaveLength(1);
    expect(inferences[0]!.confidence).toBe('high');
    expect(inferences[0]!.ruleId).toBe('service-driver-lifecycle');
  });
});

describe('Positive: windows installation inference', () => {
  test('Registry APIs + uninstall registry path strings → HIGH confidence', () => {
    const ctx: EvidenceContext = {
      ...emptyCtx(),
      imports: [{ dll: 'advapi32.dll', functions: ['RegCreateKeyExW', 'RegSetValueExW', 'RegDeleteKeyExW', 'RegOpenKeyExW'] }],
      evidence: [
        makeImportEvidence('advapi32.dll', ['RegCreateKeyExW', 'RegSetValueExW', 'RegDeleteKeyExW', 'RegOpenKeyExW'], 'evd-imp-0001'),
        makeStringEvidence('Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\MyApp', 'evd-str-0001'),
        makeStringEvidence('DisplayName', 'evd-str-0002'),
        makeStringEvidence('UninstallString', 'evd-str-0003'),
      ],
      strings: [
        makeExtractedString('Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\MyApp'),
        makeExtractedString('DisplayName'),
        makeExtractedString('UninstallString'),
      ],
    };
    const inferences = windowsInstallationRule.evaluate(ctx);
    expect(inferences).toHaveLength(1);
    expect(inferences[0]!.confidence).toBe('high');
    expect(inferences[0]!.ruleId).toBe('windows-installation');
  });
});
