/**
 * Shared domain types used across the entire codebase.
 *
 * These are the canonical representations of the domain model.
 * All production code must use these types; never invent alternative shapes.
 *
 * SAFETY INVARIANT: The uploaded binary is NEVER executed.
 * These types represent static analysis artifacts only.
 */

// ── Analysis lifecycle ───────────────────────────────────────────────────────

export type AnalysisStatus =
  | 'queued'
  | 'preparing'
  | 'extracting'
  | 'decompiling'
  | 'correlating'
  | 'reporting'
  | 'completed'
  | 'partial'
  | 'failed';

export type AnalysisPhase =
  | 'intake'
  | 'profiling'
  | 'extracting'
  | 'ghidra-analysis'
  | 'correlating'
  | 'inferring'
  | 'reconstructing'
  | 'reporting';

export interface PhaseRecord {
  phase: AnalysisPhase;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'skipped';
  startedAt?: string;
  completedAt?: string;
  durationMs?: number;
  error?: string;
}

export interface AnalysisMeta {
  id: string;
  status: AnalysisStatus;
  createdAt: string;
  updatedAt: string;
  originalFilename: string;
  storedFilename: string;
  fileSizeBytes: number;
  sha256: string;
  phases: PhaseRecord[];
  errorMessage?: string;
}

// ── Binary profile ───────────────────────────────────────────────────────────

export type PeType = 'PE32' | 'PE32+' | 'unknown';
export type Architecture = 'x86' | 'x86-64' | 'ARM' | 'ARM64' | 'unknown';
export type Subsystem =
  | 'WINDOWS_GUI'
  | 'WINDOWS_CUI'
  | 'NATIVE'
  | 'WINDOWS_CE_GUI'
  | 'EFI_APPLICATION'
  | 'unknown';

export interface PeSection {
  name: string;
  virtualAddress: string;
  virtualSize: number;
  rawSize: number;
  characteristics: string[];
  entropy?: number;
}

export interface ImportEntry {
  dll: string;
  functions: string[];
}

export interface ExportEntry {
  ordinal: number;
  name?: string;
  address: string;
}

export interface VersionInfo {
  fileVersion?: string;
  productVersion?: string;
  companyName?: string;
  productName?: string;
  description?: string;
  originalFilename?: string;
  legalCopyright?: string;
  internalName?: string;
}

export interface BinaryProfile {
  originalFilename: string;
  storedFilename: string;
  fileSizeBytes: number;
  sha256: string;
  peType: PeType;
  architecture: Architecture;
  subsystem: Subsystem;
  entryPoint: string;
  sections: PeSection[];
  imports: ImportEntry[];
  exports: ExportEntry[];
  versionInfo?: VersionInfo;
  hasSignature: boolean;
  /** High entropy is a clue, not proof of packing/malice */
  overallEntropy?: number;
}

// ── Evidence model ───────────────────────────────────────────────────────────

export type EvidenceKind =
  | 'binary-metadata'
  | 'pe-section'
  | 'import'
  | 'export'
  | 'string'
  | 'function'
  | 'function-call'
  | 'reference'
  | 'decompilation'
  | 'metadata';

export type EvidenceSource = 'pe-parser' | 'strings' | 'ghidra';

export interface Evidence {
  id: string;
  kind: EvidenceKind;
  sourceTool: EvidenceSource;
  classification: 'observed';
  summary: string;
  location?: {
    address?: string;
    offset?: number;
    functionAddress?: string;
  };
  data: unknown;
}

// ── Strings ──────────────────────────────────────────────────────────────────

export type StringCategory =
  | 'url'
  | 'hostname'
  | 'ip'
  | 'file-path'
  | 'registry-path'
  | 'sql'
  | 'protocol'
  | 'authentication'
  | 'error-message'
  | 'service-name'
  | 'dll-name'
  | 'installer-metadata'
  | 'config-filename'
  | 'other';

export interface ExtractedString {
  value: string;
  encoding: 'ascii' | 'utf-16le';
  offset: number;
  section?: string;
  category: StringCategory;
}

// ── Function profiles ────────────────────────────────────────────────────────

export interface FunctionProfile {
  address: string;
  name: string;
  autoGenerated: boolean;
  callers: string[];
  callees: string[];
  apiReferences: string[];
  stringReferences: string[];
  evidenceIds: string[];
  decompilationEvidenceIds: string[];
  selectionScore: number;
  selectionReasons: string[];
}

// ── Reconstruction types ─────────────────────────────────────────────────────

export type ConfidenceLevel = 'low' | 'medium' | 'high' | 'not-applicable';
export type InferenceClassification = 'observed' | 'inferred' | 'unknown';

export interface Inference {
  id: string;
  ruleId: string;
  category: string;
  statement: string;
  classification: 'inferred';
  confidence: ConfidenceLevel;
  evidenceIds: string[];
  rationale: string[];
  limitations: string[];
  counterEvidence?: string[];
}

export interface CandidateResponsibility {
  id: string;
  name: string;
  kind: 'candidate-responsibility';
  confidence: ConfidenceLevel;
  summary: string;
  functions: Array<{
    address: string;
    name: string;
    autoGenerated: boolean;
  }>;
  evidenceIds: string[];
  rationale: Array<{
    classification: InferenceClassification;
    text: string;
  }>;
  externalInteractions?: string[];
  limitations: string[];
}

export interface ExternalInteraction {
  id: string;
  kind: 'filesystem' | 'registry' | 'process' | 'service' | 'network' | 'database';
  description: string;
  confidence: ConfidenceLevel;
  evidenceIds: string[];
  limitations: string[];
}

export interface Unknown {
  id: string;
  question: string;
  whyItMatters: string;
  missingEvidence: string;
  howToResolve: string[];
}

export interface ModernizationRecommendation {
  id: string;
  priority: 'high' | 'medium' | 'low';
  title: string;
  description: string;
  evidenceIds: string[];
  relatedResponsibilityIds: string[];
}

// ── Canonical result ─────────────────────────────────────────────────────────

export interface ToolCoverage {
  peParser: boolean;
  strings: boolean;
  ghidra: boolean;
  ghidraError?: string;
}

export interface CanonicalResult {
  analysis: AnalysisMeta;
  binary: BinaryProfile;
  coverage: ToolCoverage;
  evidence: Evidence[];
  capabilities: Inference[];
  /** candidateComponents is the API field name; semantically these are candidate responsibilities */
  candidateComponents: CandidateResponsibility[];
  externalInteractions: ExternalInteraction[];
  dependencies: string[];
  interestingFunctions: FunctionProfile[];
  unknowns: Unknown[];
  risks: string[];
  modernization: ModernizationRecommendation[];
  limitations: string[];
}

// ── API error envelope ───────────────────────────────────────────────────────

export interface ErrorResponse {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
}
