/**
 * Call edge normalizer unit tests.
 *
 * Verifies that tiny hex addresses and unknown addresses are filtered,
 * while valid function entry addresses and known import names are kept.
 */
import { normalizeCallEdges } from '../../../modules/evidence/callEdgeNormalizer';
import { type GhidraFunction } from '../../../modules/ghidra/validator';
import { type ImportEntry } from '../../../shared/types';

// ── Test fixtures ──────────────────────────────────────────────────────────────

function makeFunction(overrides: Partial<GhidraFunction> & { address: string; name: string }): GhidraFunction {
  return {
    autoGenerated: false,
    callers: [],
    callees: [],
    referencedImports: [],
    referencedStrings: [],
    selectionScore: 0,
    selectionReasons: [],
    decompilation: null,
    ...overrides,
  };
}

const IMPORTS: ImportEntry[] = [
  { dll: 'kernel32.dll', functions: ['CreateFile', 'ReadFile', 'CloseHandle'] },
  { dll: 'user32.dll',   functions: ['MessageBoxA'] },
];

// ── Tiny address filtering ─────────────────────────────────────────────────────

describe('normalizeCallEdges — tiny address filtering', () => {
  test('filters callees with address 0x24 (raw numeric constant)', () => {
    const functions = [
      makeFunction({ address: '00401000', name: 'main',       callees: ['24', '00401100'] }),
      makeFunction({ address: '00401100', name: 'helperFunc', callees: [] }),
    ];

    const result = normalizeCallEdges(functions, IMPORTS);
    const mainEdges = result.get('00401000');

    expect(mainEdges?.callees).not.toContain('24');
    expect(mainEdges?.callees).toContain('00401100');
  });

  test('filters callees with address 0x2 (raw numeric constant)', () => {
    const functions = [
      makeFunction({ address: '00401000', name: 'main', callees: ['2', '00401100'] }),
      makeFunction({ address: '00401100', name: 'other', callees: [] }),
    ];

    const result = normalizeCallEdges(functions, IMPORTS);
    expect(result.get('00401000')?.callees).not.toContain('2');
  });

  test('filters callees with address 0xbe (raw numeric constant)', () => {
    const functions = [
      makeFunction({ address: '00401000', name: 'main', callees: ['be', '00401100'] }),
      makeFunction({ address: '00401100', name: 'other', callees: [] }),
    ];

    const result = normalizeCallEdges(functions, IMPORTS);
    expect(result.get('00401000')?.callees).not.toContain('be');
  });

  test('filters callers with tiny address', () => {
    const functions = [
      makeFunction({ address: '00401000', name: 'main', callers: ['ff'] }),
    ];

    const result = normalizeCallEdges(functions, IMPORTS);
    expect(result.get('00401000')?.callers).toHaveLength(0);
  });
});

// ── Valid address preservation ─────────────────────────────────────────────────

describe('normalizeCallEdges — valid function addresses kept', () => {
  test('keeps callee that is a known function entry address >= 0x1000', () => {
    const functions = [
      makeFunction({ address: '00401000', name: 'main',   callees: ['00401100'] }),
      makeFunction({ address: '00401100', name: 'helper', callees: [] }),
    ];

    const result = normalizeCallEdges(functions, IMPORTS);
    expect(result.get('00401000')?.callees).toContain('00401100');
  });

  test('keeps address exactly at 0x1000 boundary', () => {
    const functions = [
      makeFunction({ address: '00001000', name: 'atBoundary', callees: ['00402000'] }),
      makeFunction({ address: '00402000', name: 'target',     callees: [] }),
    ];

    const result = normalizeCallEdges(functions, IMPORTS);
    expect(result.get('00001000')?.callees).toContain('00402000');
  });

  test('all functions appear in the result map', () => {
    const functions = [
      makeFunction({ address: '00401000', name: 'fnA', callees: [] }),
      makeFunction({ address: '00402000', name: 'fnB', callees: [] }),
      makeFunction({ address: '00403000', name: 'fnC', callees: [] }),
    ];

    const result = normalizeCallEdges(functions, IMPORTS);
    expect(result.size).toBe(3);
    expect(result.has('00401000')).toBe(true);
    expect(result.has('00402000')).toBe(true);
    expect(result.has('00403000')).toBe(true);
  });
});

// ── Unknown address filtering ──────────────────────────────────────────────────

describe('normalizeCallEdges — unknown addresses filtered', () => {
  test('filters callee that is not a known function entry address', () => {
    const functions = [
      makeFunction({ address: '00401000', name: 'main', callees: ['00499999'] }),
      // 00499999 is NOT in the functions list
    ];

    const result = normalizeCallEdges(functions, IMPORTS);
    expect(result.get('00401000')?.callees).toHaveLength(0);
  });

  test('filters caller that is not a known function entry address', () => {
    const functions = [
      makeFunction({ address: '00401000', name: 'main', callers: ['00499999'] }),
    ];

    const result = normalizeCallEdges(functions, IMPORTS);
    expect(result.get('00401000')?.callers).toHaveLength(0);
  });
});

// ── Empty inputs ───────────────────────────────────────────────────────────────

describe('normalizeCallEdges — edge cases', () => {
  test('handles empty function list', () => {
    const result = normalizeCallEdges([], IMPORTS);
    expect(result.size).toBe(0);
  });

  test('handles function with no callers/callees', () => {
    const functions = [
      makeFunction({ address: '00401000', name: 'isolated', callers: [], callees: [] }),
    ];

    const result = normalizeCallEdges(functions, []);
    expect(result.get('00401000')?.callers).toHaveLength(0);
    expect(result.get('00401000')?.callees).toHaveLength(0);
  });

  test('handles 0x-prefixed addresses correctly', () => {
    const functions = [
      makeFunction({ address: '0x401000', name: 'main',   callees: ['0x401100'] }),
      makeFunction({ address: '0x401100', name: 'helper', callees: [] }),
    ];

    const result = normalizeCallEdges(functions, []);
    expect(result.get('0x401000')?.callees).toContain('0x401100');
  });
});
