/**
 * Evidence normalizer unit tests.
 */
import {
  normalizePeEvidence,
  normalizeStringEvidence,
  normalizeGhidraEvidence,
  buildEvidenceStore,
  evidenceId,
} from '../../../modules/evidence/normalizer';
import { type BinaryProfile, type ExtractedString } from '../../../shared/types';
import { type GhidraRawOutput } from '../../../modules/ghidra/validator';

// ── Test fixtures ──────────────────────────────────────────────────────────────

function makeProfile(overrides: Partial<BinaryProfile> = {}): BinaryProfile {
  return {
    originalFilename: 'test.exe',
    storedFilename: 'binary.exe',
    fileSizeBytes: 4096,
    sha256: 'abc123',
    peType: 'PE32',
    architecture: 'x86',
    subsystem: 'WINDOWS_GUI',
    entryPoint: '0x401000',
    sections: [
      { name: '.text', virtualAddress: '0x1000', virtualSize: 0x2000, rawSize: 0x2000, characteristics: ['CODE'] },
      { name: '.data', virtualAddress: '0x3000', virtualSize: 0x1000, rawSize: 0x1000, characteristics: ['INITIALIZED_DATA'] },
    ],
    imports: [
      { dll: 'kernel32.dll', functions: ['CreateFile', 'CloseHandle', 'ReadFile'] },
      { dll: 'user32.dll',   functions: ['MessageBoxA'] },
    ],
    exports: [
      { ordinal: 1, name: 'MyExport', address: '0x401100' },
    ],
    hasSignature: false,
    ...overrides,
  };
}

function makeStrings(): ExtractedString[] {
  return [
    { value: 'Hello, World!',     encoding: 'ascii',    offset: 0x100, category: 'other' },
    { value: 'http://example.com', encoding: 'ascii',    offset: 0x200, category: 'url' },
    { value: 'C:\\Windows\\temp', encoding: 'utf-16le', offset: 0x300, category: 'file-path' },
    // Duplicate — should be deduplicated
    { value: 'Hello, World!',     encoding: 'ascii',    offset: 0x400, category: 'other' },
  ];
}

function makeGhidraOutput(): GhidraRawOutput {
  return {
    programLanguage: 'x86:LE:32:default',
    entryPoint: '00401000',
    totalFunctions: 2,
    functions: [
      {
        address: '00401000',
        name: 'main',
        autoGenerated: false,
        callers: [],
        callees: ['00401100'],
        referencedImports: ['CreateFile'],
        referencedStrings: ['Hello, World!'],
        selectionScore: 5.0,
        selectionReasons: ['references 1 import(s)', 'named function'],
        decompilation: 'int main() { return 0; }',
      },
      {
        address: '00401100',
        name: 'FUN_00401100',
        autoGenerated: true,
        callers: ['00401000'],
        callees: [],
        referencedImports: [],
        referencedStrings: [],
        selectionScore: 0.0,
        selectionReasons: [],
        decompilation: null,
      },
    ],
  };
}

// ── evidenceId ─────────────────────────────────────────────────────────────────

describe('evidenceId', () => {
  test('formats with 3-char kind prefix and zero-padded index', () => {
    expect(evidenceId('binary-metadata', 0)).toBe('evd-bin-0000');
    expect(evidenceId('pe-section', 5)).toBe('evd-pe--0005');
    expect(evidenceId('import', 99)).toBe('evd-imp-0099');
    expect(evidenceId('string', 1000)).toBe('evd-str-1000');
  });
});

// ── normalizePeEvidence ────────────────────────────────────────────────────────

describe('normalizePeEvidence', () => {
  let evidence: ReturnType<typeof normalizePeEvidence>;

  beforeEach(() => {
    evidence = normalizePeEvidence(makeProfile());
  });

  test('all evidence has classification "observed"', () => {
    for (const evd of evidence) {
      expect(evd.classification).toBe('observed');
    }
  });

  test('all evidence has sourceTool "pe-parser"', () => {
    for (const evd of evidence) {
      expect(evd.sourceTool).toBe('pe-parser');
    }
  });

  test('includes exactly one binary-metadata evidence', () => {
    const meta = evidence.filter(e => e.kind === 'binary-metadata');
    expect(meta).toHaveLength(1);
  });

  test('includes one pe-section evidence per section', () => {
    const sections = evidence.filter(e => e.kind === 'pe-section');
    expect(sections).toHaveLength(2); // .text and .data
  });

  test('pe-section evidence has correct section names', () => {
    const sections = evidence.filter(e => e.kind === 'pe-section');
    const names = sections.map(s => (s.data as { name: string }).name);
    expect(names).toContain('.text');
    expect(names).toContain('.data');
  });

  test('includes one import evidence per DLL', () => {
    const imports = evidence.filter(e => e.kind === 'import');
    expect(imports).toHaveLength(2); // kernel32.dll and user32.dll
  });

  test('import evidence contains function list', () => {
    const k32 = evidence.find(e => e.kind === 'import' && (e.data as { dll: string }).dll === 'kernel32.dll');
    expect(k32).toBeDefined();
    expect((k32!.data as { functions: string[] }).functions).toContain('CreateFile');
  });

  test('includes one export evidence per export', () => {
    const exports = evidence.filter(e => e.kind === 'export');
    expect(exports).toHaveLength(1);
  });

  test('all IDs are unique', () => {
    const ids = evidence.map(e => e.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  test('profile with no exports produces no export evidence', () => {
    const profileNoExports = makeProfile({ exports: [] });
    const evd = normalizePeEvidence(profileNoExports);
    expect(evd.filter(e => e.kind === 'export')).toHaveLength(0);
  });
});

// ── normalizeStringEvidence ───────────────────────────────────────────────────

describe('normalizeStringEvidence', () => {
  test('deduplicates strings with the same value', () => {
    const strings = makeStrings();
    const evidence = normalizeStringEvidence(strings, 0);
    // 4 input strings but "Hello, World!" appears twice — expect 3 unique
    expect(evidence).toHaveLength(3);
  });

  test('all evidence has classification "observed"', () => {
    const evidence = normalizeStringEvidence(makeStrings(), 0);
    for (const evd of evidence) {
      expect(evd.classification).toBe('observed');
    }
  });

  test('all evidence has sourceTool "strings"', () => {
    const evidence = normalizeStringEvidence(makeStrings(), 0);
    for (const evd of evidence) {
      expect(evd.sourceTool).toBe('strings');
    }
  });

  test('evidence has offset in location', () => {
    const evidence = normalizeStringEvidence(makeStrings(), 0);
    for (const evd of evidence) {
      expect(evd.location?.offset).toBeDefined();
    }
  });

  test('respects offset parameter for ID generation', () => {
    const ev0 = normalizeStringEvidence(makeStrings(), 0);
    const ev10 = normalizeStringEvidence(makeStrings(), 10);
    // IDs should differ because offsets differ
    expect(ev0[0]!.id).not.toBe(ev10[0]!.id);
  });
});

// ── normalizeGhidraEvidence ───────────────────────────────────────────────────

describe('normalizeGhidraEvidence', () => {
  test('produces function evidence for each function', () => {
    const ghidra = makeGhidraOutput();
    const evidence = normalizeGhidraEvidence(ghidra, 0);
    const fns = evidence.filter(e => e.kind === 'function');
    expect(fns).toHaveLength(2);
  });

  test('produces decompilation evidence only for functions with decompilation', () => {
    const ghidra = makeGhidraOutput();
    const evidence = normalizeGhidraEvidence(ghidra, 0);
    const decomps = evidence.filter(e => e.kind === 'decompilation');
    // Only 'main' has decompilation
    expect(decomps).toHaveLength(1);
  });

  test('decompilation evidence has functionAddress in location', () => {
    const ghidra = makeGhidraOutput();
    const evidence = normalizeGhidraEvidence(ghidra, 0);
    const decomp = evidence.find(e => e.kind === 'decompilation');
    expect(decomp?.location?.functionAddress).toBe('00401000');
  });

  test('all evidence has sourceTool "ghidra"', () => {
    const evidence = normalizeGhidraEvidence(makeGhidraOutput(), 0);
    for (const evd of evidence) {
      expect(evd.sourceTool).toBe('ghidra');
    }
  });
});

// ── buildEvidenceStore ─────────────────────────────────────────────────────────

describe('buildEvidenceStore', () => {
  test('all IDs are unique across the full store', () => {
    const evidence = buildEvidenceStore(makeProfile(), makeStrings(), makeGhidraOutput());
    const ids = evidence.map(e => e.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  test('includes PE, string, and Ghidra evidence when all provided', () => {
    const evidence = buildEvidenceStore(makeProfile(), makeStrings(), makeGhidraOutput());
    const kinds = new Set(evidence.map(e => e.kind));
    expect(kinds.has('binary-metadata')).toBe(true);
    expect(kinds.has('pe-section')).toBe(true);
    expect(kinds.has('import')).toBe(true);
    expect(kinds.has('string')).toBe(true);
    expect(kinds.has('function')).toBe(true);
    expect(kinds.has('decompilation')).toBe(true);
  });

  test('omits Ghidra evidence when ghidra param not provided', () => {
    const evidence = buildEvidenceStore(makeProfile(), makeStrings());
    const kinds = new Set(evidence.map(e => e.kind));
    expect(kinds.has('function')).toBe(false);
    expect(kinds.has('decompilation')).toBe(false);
  });

  test('all evidence has classification "observed"', () => {
    const evidence = buildEvidenceStore(makeProfile(), makeStrings(), makeGhidraOutput());
    for (const evd of evidence) {
      expect(evd.classification).toBe('observed');
    }
  });
});
