/**
 * Candidate responsibility builder.
 *
 * For each HIGH or MEDIUM confidence inference, groups related function
 * profiles and builds a CandidateResponsibility.
 *
 * Invariants:
 * - Every evidenceId in a CandidateResponsibility must be present in the
 *   evidence array passed in.
 * - Function names starting with FUN_ have autoGenerated=true and are never
 *   presented as recovered source names.
 * - Descriptive technical names only — no class names like InstallationManager.
 */
import { v4 as uuidv4 } from 'uuid';
import {
  type Inference,
  type FunctionProfile,
  type Evidence,
  type CandidateResponsibility,
  type InferenceClassification,
} from '../../shared/types.js';

const CATEGORY_NAMES: Record<string, string> = {
  installation: 'Windows installation and uninstallation handling',
  persistence: 'Registry-backed configuration and settings persistence',
  service: 'Windows service and driver lifecycle management',
  filesystem: 'Filesystem deployment and file management',
  process: 'External process creation and management',
  network: 'Network communication',
  database: 'Database access and query execution',
  authentication: 'Authentication and credential handling',
  cryptography: 'Cryptographic operations',
};

const CATEGORY_LIMITATIONS: Record<string, string[]> = {
  installation: [
    'Static analysis cannot determine whether installation runs to completion.',
    'Registry keys written cannot be enumerated without runtime observation.',
  ],
  persistence: [
    'Static analysis cannot determine which registry paths are read/written at runtime.',
  ],
  service: [
    'Static analysis cannot identify which specific service names are managed.',
    'Driver loading behavior cannot be confirmed without kernel debugging.',
  ],
  filesystem: [
    'Static analysis cannot enumerate which files are created, copied, or deleted.',
    'Exact deployment paths are not recoverable without runtime tracing.',
  ],
  process: [
    'Static analysis cannot determine which binaries are launched or their arguments.',
  ],
  network: [
    'Static analysis cannot determine what data is transmitted.',
    'Endpoints and hostnames cannot be confirmed without runtime observation.',
  ],
  database: [
    'Static analysis cannot identify which database engine or schema is used.',
    'SQL strings may not correspond to executed queries.',
  ],
  authentication: [
    'Static analysis cannot assess security of credential handling.',
    'Authentication flow cannot be confirmed without runtime tracing.',
  ],
  cryptography: [
    'Static analysis cannot determine key management practices.',
    'Cryptographic algorithm and mode cannot always be inferred from API names alone.',
  ],
};

/**
 * Build a set of evidence IDs from the provided evidence array, for fast lookup.
 */
function validEvidenceIdSet(evidence: Evidence[]): Set<string> {
  return new Set(evidence.map(e => e.id));
}

/**
 * Find function profiles that share evidence IDs with the given inference.
 */
function correlatedFunctions(
  inference: Inference,
  functionProfiles: FunctionProfile[],
): FunctionProfile[] {
  const inferenceEvSet = new Set(inference.evidenceIds);
  return functionProfiles.filter(fp =>
    fp.evidenceIds.some(eid => inferenceEvSet.has(eid)) ||
    fp.decompilationEvidenceIds.some(eid => inferenceEvSet.has(eid)),
  );
}

export function buildCandidateResponsibilities(
  inferences: Inference[],
  functionProfiles: FunctionProfile[],
  evidence: Evidence[],
): CandidateResponsibility[] {
  const validIds = validEvidenceIdSet(evidence);
  const candidates: CandidateResponsibility[] = [];

  for (const inference of inferences) {
    if (inference.confidence !== 'high' && inference.confidence !== 'medium') {
      continue;
    }

    // Filter evidence IDs to only those that actually exist
    const safeEvidenceIds = inference.evidenceIds.filter(id => validIds.has(id));

    const related = correlatedFunctions(inference, functionProfiles);
    const name = CATEGORY_NAMES[inference.category] ?? inference.category;
    const limits = CATEGORY_LIMITATIONS[inference.category] ?? [];

    const rationale: Array<{ classification: InferenceClassification; text: string }> = [
      ...inference.rationale.map(text => ({
        classification: 'observed' as InferenceClassification,
        text,
      })),
      {
        classification: 'inferred' as InferenceClassification,
        text: inference.statement,
      },
    ];

    if (inference.limitations.length > 0) {
      for (const lim of inference.limitations) {
        rationale.push({ classification: 'unknown', text: lim });
      }
    }

    candidates.push({
      id: uuidv4(),
      name,
      kind: 'candidate-responsibility',
      confidence: inference.confidence,
      summary: inference.statement,
      functions: related.map(fp => ({
        address: fp.address,
        name: fp.name,
        autoGenerated: fp.autoGenerated,
      })),
      evidenceIds: safeEvidenceIds,
      rationale,
      limitations: [...limits, ...inference.limitations].filter((v, i, arr) => arr.indexOf(v) === i),
    });
  }

  return candidates;
}
