/**
 * Candidate responsibility builder.
 *
 * For each HIGH or MEDIUM confidence inference, groups related function
 * profiles and builds a CandidateResponsibility.
 *
 * Invariants:
 * - Every evidenceId in a CandidateResponsibility must be present in the
 *   evidence array passed in.
 * - Function names starting with FUN_ have autoGenerated=true and are never
 *   presented as recovered source names.
 * - Descriptive technical names only — no class names like InstallationManager.
 */
import { v4 as uuidv4 } from 'uuid';
import {
  type Inference,
  type FunctionProfile,
  type Evidence,
  type CandidateResponsibility,
  type InferenceClassification,
} from '../../shared/types.js';

const CATEGORY_NAMES: Record<string, string> = {
  installation: 'Windows installation and uninstallation handling',
  persistence: 'Registry-backed configuration and settings persistence',
  service: 'Windows service and driver lifecycle management',
  filesystem: 'Filesystem deployment and file management',
  process: 'External process creation and management',
  network: 'Network communication',
  database: 'Database access and query execution',
  authentication: 'Authentication and credential handling',
  cryptography: 'Cryptographic operations',
};

const CATEGORY_LIMITATIONS: Record<string, string[]> = {
  installation: [
    'Static analysis cannot determine whether installation runs to completion.',
    'Registry keys written cannot be enumerated without runtime observation.',
  ],
  persistence: [
    'Static analysis cannot determine which registry paths are read/written at runtime.',
  ],
  service: [
    'Static analysis cannot identify which specific service names are managed.',
    'Driver loading behavior cannot be confirmed without kernel debugging.',
  ],
  filesystem: [
    'Static analysis cannot enumerate which files are created, copied, or deleted.',
    'Exact deployment paths are not recoverable without runtime tracing.',
  ],
  process: [
    'Static analysis cannot determine which binaries are launched or their arguments.',
  ],
  network: [
    'Static analysis cannot determine what data is transmitted.',
    'Endpoints and hostnames cannot be confirmed without runtime observation.',
  ],
  database: [
    'Static analysis cannot identify which database engine or schema is used.',
    'SQL strings may not correspond to executed queries.',
  ],
  authentication: [
    'Static analysis cannot assess security of credential handling.',
    'Authentication flow cannot be confirmed without runtime tracing.',
  ],
  cryptography: [
    'Static analysis cannot determine key management practices.',
    'Cryptographic algorithm and mode cannot always be inferred from API names alone.',
  ],
};

const MAX_KEY_APIS = 15;
const MAX_KEY_STRINGS = 12;
const MAX_STRING_DISPLAY_LEN = 120;

/**
 * Build a set of evidence IDs from the provided evidence array, for fast lookup.
 */
function validEvidenceIdSet(evidence: Evidence[]): Set<string> {
  return new Set(evidence.map(e => e.id));
}

/**
 * Extract the API names referenced by the import/function-call evidence items
 * that are included in the inference's evidenceIds.
 * Evidence summaries have the form "Import: <ApiName> from <dll>" or
 * "Function call: <ApiName>".
 */
function apisFromInferenceEvidence(inference: Inference, evidence: Evidence[]): Set<string> {
  const inferenceEvSet = new Set(inference.evidenceIds);
  const apis = new Set<string>();
  for (const ev of evidence) {
    if (!inferenceEvSet.has(ev.id)) continue;
    if (ev.kind !== 'import' && ev.kind !== 'function-call') continue;
    // Summary format: "Import: <ApiName> from <dll>" or "Function call: <ApiName> at <addr>"
    const match = ev.summary.match(/^(?:Import|Function call):\s*([^\s@(]+)/i);
    if (match && match[1]) {
      apis.add(match[1].toLowerCase());
    }
  }
  return apis;
}

/**
 * Find function profiles correlated with the given inference.
 *
 * Primary: evidence-ID overlap (function/decompilation evidence IDs vs. inference evidenceIds).
 * Secondary: API-reference overlap — if the inference is based on import evidence that
 *   names specific APIs, associate function profiles that call those same APIs.
 *   This bridges the gap where inference evidenceIds only contain import-kind evidence
 *   while function evidenceIds contain function-kind evidence.
 */
function correlatedFunctions(
  inference: Inference,
  functionProfiles: FunctionProfile[],
  evidence: Evidence[],
): FunctionProfile[] {
  const inferenceEvSet = new Set(inference.evidenceIds);

  // Primary: direct evidence-ID overlap
  const primary = new Set<string>(); // addresses already matched
  const result: FunctionProfile[] = [];
  for (const fp of functionProfiles) {
    if (
      fp.evidenceIds.some(eid => inferenceEvSet.has(eid)) ||
      fp.decompilationEvidenceIds.some(eid => inferenceEvSet.has(eid))
    ) {
      primary.add(fp.address);
      result.push(fp);
    }
  }

  // Secondary: API-reference overlap via import evidence names
  const inferenceApis = apisFromInferenceEvidence(inference, evidence);
  if (inferenceApis.size > 0) {
    for (const fp of functionProfiles) {
      if (primary.has(fp.address)) continue; // already included
      if (fp.apiReferences.some(api => inferenceApis.has(api.toLowerCase()))) {
        result.push(fp);
      }
    }
  }

  return result;
}

/**
 * Derive bounded deduplicated API list from correlated function profiles.
 * Preserves original casing but deduplicates case-insensitively.
 */
function deriveKeyApis(related: FunctionProfile[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const fp of related) {
    for (const api of fp.apiReferences) {
      const key = api.toLowerCase();
      if (!seen.has(key)) {
        seen.add(key);
        result.push(api);
        if (result.length >= MAX_KEY_APIS) return result;
      }
    }
  }
  return result;
}

/**
 * Derive bounded unique string list from correlated function profiles.
 * Skips clearly unusable strings (empty or too short after trimming).
 */
function deriveKeyStrings(related: FunctionProfile[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const fp of related) {
    for (const s of fp.stringReferences) {
      const trimmed = s.trim();
      if (trimmed.length < 4) continue;
      const display = trimmed.length > MAX_STRING_DISPLAY_LEN
        ? trimmed.slice(0, MAX_STRING_DISPLAY_LEN) + '…'
        : trimmed;
      if (!seen.has(display)) {
        seen.add(display);
        result.push(display);
        if (result.length >= MAX_KEY_STRINGS) return result;
      }
    }
  }
  return result;
}

export function buildCandidateResponsibilities(
  inferences: Inference[],
  functionProfiles: FunctionProfile[],
  evidence: Evidence[],
): CandidateResponsibility[] {
  const validIds = validEvidenceIdSet(evidence);
  const candidates: CandidateResponsibility[] = [];

  for (const inference of inferences) {
    if (inference.confidence !== 'high' && inference.confidence !== 'medium') {
      continue;
    }

    // Filter evidence IDs to only those that actually exist
    const safeEvidenceIds = inference.evidenceIds.filter(id => validIds.has(id));

    const related = correlatedFunctions(inference, functionProfiles, evidence);
    const name = CATEGORY_NAMES[inference.category] ?? inference.category;
    const limits = CATEGORY_LIMITATIONS[inference.category] ?? [];

    // Rationale classification:
    // - inference.rationale entries explain WHY the rule fired; they are 'inferred'
    //   context notes, not directly observed facts — keep them as 'inferred'.
    // - The inference statement itself is 'inferred'.
    // - Limitations are 'unknown'.
    const rationale: Array<{ classification: InferenceClassification; text: string }> = [
      ...inference.rationale.map(text => ({
        classification: 'inferred' as InferenceClassification,
        text,
      })),
      {
        classification: 'inferred' as InferenceClassification,
        text: inference.statement,
      },
    ];

    if (inference.limitations.length > 0) {
      for (const lim of inference.limitations) {
        rationale.push({ classification: 'unknown' as InferenceClassification, text: lim });
      }
    }

    const keyApis = deriveKeyApis(related);
    const keyStrings = deriveKeyStrings(related);

    candidates.push({
      id: uuidv4(),
      name,
      kind: 'candidate-responsibility',
      confidence: inference.confidence,
      summary: inference.statement,
      functions: related.map(fp => ({
        address: fp.address,
        name: fp.name,
        autoGenerated: fp.autoGenerated,
      })),
      evidenceIds: safeEvidenceIds,
      rationale,
      limitations: [...limits, ...inference.limitations].filter((v, i, arr) => arr.indexOf(v) === i),
      ...(keyApis.length > 0 ? { keyApis } : {}),
      ...(keyStrings.length > 0 ? { keyStrings } : {}),
    });
  }

  return candidates;
}
